version: '3.6'

services:
  builder:
    build: 
        context: ./dockers
        dockerfile: Dockerfile 
    container_name: laravel7 
    ports:
        - 9898:80
    restart: always
    volumes:
        - ./application/:/var/www
        - ./logs/nginx:/var/log/nginx
        - ./dockers/php-fpm/config/php.ini:/etc/php7/php.ini
        - ./dockers/nginx/nginx.conf:/etc/nginx/nginx.conf 
        #- ./dockers/nginx/conf.d:/etc/nginx/conf.d 
    networks:
        - external-network
    
networks:
  external-network: 
    external:
      name: your-network 